#!/bin/sh /etc/rc.common

USE_PROCD=1
START=90
STOP=10
PROG=/usr/bin/paqet

start_instance() {
	local cfg="$1"
	local enabled
	local config
	config_get enabled "$cfg" enabled "0"
	[ "$enabled" -eq 0 ] && return 0
	config_get config "$cfg" config
	[ -z "$config" ] && return 1
	[ -f "$config" ] || {
	logger -s -t paqet "Config file $config not found"
	return 1
	}
	procd_open_instance "paqet_$cfg"
	procd_set_param command "$PROG" run -c "$config"
	procd_set_param respawn
#For debugging
#	procd_set_param stdout 1
#	procd_set_param stderr 1
	procd_close_instance
}
start_service() {
	config_load paqet
	config_foreach start_instance instance
}
